#! /usr/bin/env node

function startCmd() {
  const argv = require('yargs')
  .commandDir('cmds')
  .demandCommand()
  .help()
  .argv
}
try {
   var daemon = require("daemonize2").setup({
    main: "js4eos_bg",
    name: "js4eos_bg",
    pidfile: require('path').join(require('os').homedir(), ".js4eos_bg.pid"),
  });
  var pid = daemon.status();
  if (!pid) {
    // console.log("new start")
    daemon.start();
    daemon.on('started', () => {
      startCmd();
    });
  } else {
    startCmd();
  }
} catch(e) {
}
