var request = require('request');
var path = require('path');
var fs = require('fs');
var Config = require('./config').getConfig()
var Utils = require("./utils")

exports.compile = function(file, targetFile) {
  return new Promise(function(resolve, reject) {
    var req = request.post(Config.serviceUrl + "/compile", function (err, response, data) {
      // if (data) {
      //   resolve(data);
      // } else {
      //   reject(data);
      // }
      // console.log(data)
      data = JSON.parse(data);
      if (data.file) {
        Utils.downloadFile(Config.serviceUrl + "/" + data.file, targetFile).then(() => {
          data.file = targetFile;
          resolve(data);
        })
      }
    });
    try {
      var form = req.form();
      form.append('file', fs.createReadStream(file), {
        filename: path.basename(file),
        contentType: 'text/plain'
      });
    } catch(e) {
      console.log(e)
    }
  });
}

exports.abi = function(file, targetFile) {
  return new Promise(function(resolve, reject) {
    var req = request.post(Config.serviceUrl + "/abi", function (err, response, data) {
      data = JSON.parse(data);
      if (data.file) {
        Utils.downloadFile(Config.serviceUrl + "/" + data.file, targetFile).then(() => {
          try {
            let data = fs.readFileSync(targetFile, 'utf-8');
            data = data.toString().replace("generated by eosio-abigen", "generated by js4eos")
            fs.writeFileSync(targetFile, data)
          } catch(e) {
            console.log(e)
          }
          data.file = targetFile;
          resolve(data);
        })
      }
    });
    try {
      var form = req.form();
      form.append('file', fs.createReadStream(file), {
        filename: path.basename(file),
        contentType: 'text/plain'
      });
    } catch(e) {
      console.log(e)
    }
  });
}