var request = require('request');
var path = require('path');
var fs = require('fs');
var Config = require('./config').getConfig()
var Utils = require("./utils")

function compileInner(file, targetFile) {
  return new Promise(function(resolve, reject) {
    var req = request.post(Config.serviceUrl + "/compile", function (err, response, data) {
      data = JSON.parse(data);
      if (data.file) {
        Utils.downloadFile(Config.serviceUrl + "/" + data.file, targetFile).then(() => {
          data.file = targetFile;
          resolve(data);
        })
      }
    });
    try {
      var form = req.form();
      form.append('file', fs.createReadStream(file), {
        filename: path.basename(file),
        contentType: 'text/plain'
      });
    } catch(e) {
      console.log(e)
    }
  });
}

exports.compile = async function(file, targetFile) {
    let codeDir = require('path').dirname(file)
    let fileName = require('path').basename(file)
    let pos = fileName.lastIndexOf(".")
    let realFileName = fileName.slice(0, pos)
    let ext = '';
    if (pos >= 0) {
      ext = fileName.slice(pos+1)
    }
    if (ext != 'cpp') {
      return {
        stderr:'must be a cpp file'
      }
    }
    let zipFile = require('os').tmpdir() + "/" + realFileName + ".zip"
    await Utils.archiveCode(codeDir, zipFile)
    let ret = await compileInner(zipFile, targetFile);
    return ret;
}

function abiInnner(file, targetFile) {
  return new Promise(function(resolve, reject) {
    var req = request.post(Config.serviceUrl + "/abi", function (err, response, data) {
      data = JSON.parse(data);
      if (data.file) {
        Utils.downloadFile(Config.serviceUrl + "/" + data.file, targetFile).then(() => {
          try {
            let data = fs.readFileSync(targetFile, 'utf-8');
            data = data.toString().replace("generated by eosio-abigen", "generated by js4eos")
            fs.writeFileSync(targetFile, data)
          } catch(e) {
            console.log(e)
          }
          data.file = targetFile;
          resolve(data);
        })
      }
    });
    try {
      var form = req.form();
      form.append('file', fs.createReadStream(file), {
        filename: path.basename(file),
        contentType: 'text/plain'
      });
    } catch(e) {
      console.log(e)
    }
  });
}

exports.abi = async function(file, targetFile) {
  let codeDir = require('path').dirname(file)
  let fileName = require('path').basename(file)
  let pos = fileName.lastIndexOf(".")
  let realFileName = fileName.slice(0, pos)
  let ext = '';
  if (pos >= 0) {
    ext = fileName.slice(pos+1)
  }
  if (ext != 'cpp') {
    return {
      stderr:'must be a cpp file'
    }
  }
  let zipFile = require('os').tmpdir() + "/" + realFileName + ".zip"
  await Utils.archiveCode(codeDir, zipFile)
  let ret = await abiInnner(zipFile, targetFile);
  return ret;
}